version: '3'

services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_MONGO_PASSWORD}"
    ports:
      - "${DB_MONGO_PORT}:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - mongo-network

volumes:
  mongodata:

networks:
  mongo-network:
    driver: bridge